export const LIST_GENDER = [
  { value: "all", label: "All" },
  { value: "action", label: "Action" },
  { value: "adventure", label: "Adventure" },
  { value: "animation", label: "Animation" },
  { value: "biography", label: "Biography" },
  { value: "comedy", label: "Comedy" },
  { value: "crime", label: "Crime" },
  { value: "documentary", label: "Documentary" },
  { value: "drama", label: "Drama" },
  { value: "family", label: "Family" },
  { value: "fantasy", label: "Fantasy" },
  { value: "film-noir", label: "Film-Noir" },
  { value: "game-show", label: "Game-Show" },
  { value: "history", label: "History" },
  { value: "horror", label: "Horror" },
  { value: "music", label: "Music" },
  { value: "musical", label: "Musical" },
  { value: "mystery", label: "Mystery" },
  { value: "news", label: "News" },
  { value: "reality-tv", label: "Reality-TV" },
  { value: "romance", label: "Romance" },
  { value: "sci-fi", label: "Sci-Fi" },
  { value: "sport", label: "Sport" },
  { value: "talk-show", label: "Talk-Show" },
  { value: "thriller", label: "Thriller" },
  { value: "war", label: "War" },
  { value: "western", label: "Western" },
];

export const LIST_YEAR = [
  { value: "0", label: "All" },
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2020-2024", label: "2020-now" },
  { value: "2010-2024", label: "2010-now" },
  { value: "2010-2019", label: "2010-2019" },
  { value: "2000-2009", label: "2000-2009" },
  { value: "1990-1999", label: "1990-1999" },
  { value: "1980-1989", label: "1980-1989" },
  { value: "1970-1979", label: "1970-1979" },
  { value: "1950-1969", label: "1950-1969" },
  { value: "1900-1949", label: "1900-1949" },
];

export const ORDER_BY = [
  { value: "latest", label: "Latest" },
  { value: "oldest", label: "Oldest" },
  { value: "featured", label: "Featured" },
  { value: "seeds", label: "Seeds" },
  { value: "peers", label: "Peers" },
  { value: "year", label: "Year" },
  { value: "rating", label: "IMDb Rating" },
  { value: "likes", label: "YTS Likes" },
  { value: "rt_audience", label: "RT Audience" },
  { value: "alphabetical", label: "Alphabetical" },
  { value: "downloads", label: "Downloads" },
];
